options:
  url: http://localhost:8081/api/v1/stocks
  api-key: fred123

server:
  port: 8090

spring:
  datasource:
    url: jdbc:sqlserver://localhost;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Weonlyusesqltogether2020

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update
    show-sql: true